name: Disabled Workflow

on:
  # This workflow is intentionally disabled
  push:
    branches: [ "none" ]
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: echo "This workflow is intentionally disabled. Deployment is handled by npm run deploy." 